### ISSUE TITLE
Correct CUDA version to have both Pytorch and Keras (Tensorflow)

### ISSUE THREAD

**Issue by DimitriosBellos** [ZauggGroup/DeePiCt#11]
Dear DeePiCt developers,

I am in the process of installing DeePiCt, however from your instructions (https://github.com/ZauggGroup/DeePiCt#2-installation) both PyTorch and Keras are needed. To install either of them properly, consideration regarding the required CUDA version is needed. 

As it explaned [here](https://pytorch.org/get-started/locally/) for the most recent PyTorch version (1.13.1) and [here](https://pytorch.org/get-started/previous-versions/) for previous versions, some of the most recent CUDA versions that PyTorch can support are CUDA 10.2, 11.0, 11.1, 11.3, 11.6 or 11.7 .  Naturally, specific PyTorch versions support specific CUDA versions as it can be seen in the links I mentioned earlier.

Simarly, Keras (and Tensorflow, which after investigation I found that it is needed in the DeePiCt, see [here](https://github.com/ZauggGroup/DeePiCt/blob/db8a35a0eaaed41848f746d2250ba177c85f0951/2d_cnn/scripts/UNet.py#L4)) require CUDA 10.0, 10.1, 11.0 or 11.2 as explained [here](https://www.tensorflow.org/install/source#gpu). I mention the different Tensoflow versions as in the [Keras website](https://keras.io/getting_started/) they suggest to install Keras by installing Tensorflow.

My question is under what CUDA version was DeePiCt tested? Can you also provide the exact PyTorch and Tensorflow version that were used?

**Comment by frosinastojanovska** [comment]
Dear @DimitriosBellos, 

You can find [here](https://github.com/ZauggGroup/DeePiCt/blob/main/2d_cnn/envs/keras-env.yaml) the version of tensorflow, keras and cuda that were used. For pytorch, installing the latest version from conda should work.

**Comment by DimitriosBellos** [comment]
Dear @frosinastojanovska,

Thank you for your help. I kinda understand now. 2D_CNN uses Tensorflow/Keras (as shown [here](https://github.com/ZauggGroup/DeePiCt/blob/main/2d_cnn/envs/keras-env.yaml) tested with CUDA 10.0) and 3D_CNN uses PyTorch (as shown [here](https://github.com/ZauggGroup/DeePiCt/blob/main/3d_cnn/environment.yaml). I believe a neat solution could be to create 2 different environments using the environment.yaml files. One to run 2d_cnn and another to run 3d_cnn.

**Comment by frosinastojanovska** [comment]
Dear @DimitriosBellos,

Yes, that's correct. While running the pipeline, snakemake will create these separate environments for 2D CNN and 3D CNN, and ideally, you don't need to worry about that. Let us know if something is not working with the installations.
