### ISSUE TITLE
how to download the demo data in 3D notebook

### ISSUE THREAD

**Issue by JunMa11** [ZauggGroup/DeePiCt#14]
Thanks for sharing the awesome work.

I run into the following error for the 3D jupyter-notebook. How can I download the 180426_005 sample data? It's empty currently. 

![image](https://user-images.githubusercontent.com/19947331/226236236-8dda0ec0-2f85-4411-b8d7-4cee979ccebc.png)

**Comment by JunMa11** [comment]
Hi @frosinastojanovska ,

Thanks for your guidance very much. 

I have another quick question. Which image set is the annotation in the following public data?

https://www.ebi.ac.uk/empiar/EMPIAR-10989/

**Comment by frosinastojanovska** [comment]
Hi @JunMa11, as I understood from the question, do you want the ground truth annotation for the provided tomograms from the EMPIAR entry? If that is what you look for, you can find it here: 
![image](https://user-images.githubusercontent.com/17936312/227464707-345fbd66-5082-4afa-95af-05cb7e06c16a.png)

**Comment by JunMa11** [comment]
Hi @frosinastojanovska ,

Thanks for your quick reply very much. It helps me a lot.

Based on the readme file, the following six files are image-label pairs, which can be used to train the segmentation model, right?

![image](https://user-images.githubusercontent.com/19947331/227543334-3744cb5a-9ed9-4f1e-81ac-98d932bdebe4.png)

**Comment by frosinastojanovska** [comment]
Hi @JunMa11, yes for actin segmentation training those are the pairs of files with data and ground truth labels.

**Comment by JunMa11** [comment]
Thank you so much:)
