### ISSUE TITLE
Segmentation_evaluation with tomo_id with leading 0's [Minor issue]

### ISSUE THREAD

**Issue by rkjensen** [ZauggGroup/DeePiCt#18]
Hi Frosina,

When using the segmentation_evaluation part of DeePiCt 3dcnn I ran into the issue that you cannot have leading 0's in the tomogram ids. 

E.g. I had a tomogram named 00345, which had worked to perform the full pipeline (from training to prediction) but when I performed segmentation evaluation I run into the issue that the tomo_df (line 64 in the segmenation evaluation script):
`    tomo_df = df[df[DTHeader.tomo_name] == tomo_name]`
^leads to an empty dataframe. In the next line when this is then used to get the path to the membrane mask it fails:
`   target_path = tomo_df.iloc[0][clean_mask_name]`

Checking the value of tomo_name showed that the leading zero's were removed (whereas they were still present in the actual dataframe). My quick fix was just to rename the tomograms in the metadata file.

Best,
Rasmus

**Comment by frosinastojanovska** [comment]
The commit 03986ad solved this issue
