### ISSUE TITLE
Installing with cuda 11.7 and gpu support

### ISSUE THREAD

**Issue by brisvag** [ZauggGroup/DeePiCt#8]
I had some troubles setting up the environment following the instructions in the readme; I finally managed, so I thought to share here in case other encounter the same issues and in case you think it's worth updating the readme:

- I had to restrict python to 3.8, otherwise the required `keras-gpu=2.3.1` could not be installed: 
```
mamba create -c conda-forge -c bioconda -n snakemake snakemake==5.13.0 python=3.8
```
- Without specifically asking for it (and using conda-forge) I was getting the cpu-only `pytorch`: 
```
mamba install -c conda-forge pytorch-gpu torchvision
```
- conda-forge was needed for `openssl` dependency for keras:
```
mamba install -c conda-forge keras-gpu=2.3.1
```
- I had to tell cuda which devices to use with
```
export CUDA_VISIBLE_DEVICES=0,1,2,3
```

After all this, I finally got `True` out of:
```
python -c "import torch; print(torch.cuda.is_available())"
```

Hope this helps :)

**Comment by frosinastojanovska** [comment]
Hi @brisvag, many thanks for pointing this out! I updated the installation instructions accordingly :).
